name: CI - Train and Save the Model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-model:
    name: Train and Save Model
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Train the model
        run: |
          python train.py
      
      - name: Save the trained model as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-${{ matrix.python-version }}-${{ github.run_id }}